name: Continuous Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'webpack.dev.js'
      - 'jest.config.js'
      - '.gitignore'
      - '.eslint*'
      - '.husky'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Build
        run: |
          npm run build

      - name: Push to dist-build branch
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: dist-build
          folder: dist